-- Taskora professional payment system foundation.
-- Provider API calls remain server-side; this migration owns durable state,
-- access control, idempotency and verified-payment activation.

create extension if not exists pgcrypto;

create table if not exists public.payment_settings (
  id boolean primary key default true check (id),
  payment_enabled boolean not null default false,
  provider_name text,
  currency text not null default 'BDT',
  merchant_name text not null default 'Taskora',
  merchant_logo text,
  support_phone text,
  support_email text,
  payment_success_message text not null default 'আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে।',
  payment_failed_message text not null default 'পেমেন্ট সম্পন্ন করা যায়নি। আবার চেষ্টা করুন।',
  invoice_footer text,
  terms_text text,
  micro_job_activation_price numeric(12,2),
  verification_price numeric(12,2),
  verification_enabled boolean not null default true,
  verification_duration_days integer,
  updated_at timestamptz not null default now()
);

insert into public.payment_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_id text not null unique,
  transaction_id text unique,
  provider_transaction_id text unique,
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'BDT',
  payment_method text,
  status text not null default 'pending' check (status in ('pending','processing','paid','failed','cancelled','refunded')),
  payment_type text not null check (payment_type in ('micro_jobs','verification','reselling','other')),
  item_id text,
  item_name text not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  provider_response jsonb,
  provider_checkout_url text,
  provider_session_id text unique,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  cancelled_at timestamptz,
  failed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists payments_user_created_idx on public.payments(user_id, created_at desc);
create index if not exists payments_status_created_idx on public.payments(status, created_at desc);
create index if not exists payments_type_created_idx on public.payments(payment_type, created_at desc);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_id uuid not null unique references public.payments(id) on delete cascade,
  customer_name text,
  customer_email text,
  customer_phone text,
  item_name text not null,
  item_description text,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  currency text not null default 'BDT',
  status text not null default 'pending' check (status in ('pending','paid','failed','cancelled','refunded')),
  transaction_id text,
  payment_method text,
  issued_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists invoices_user_issued_idx on public.invoices(user_id, issued_at desc);

create table if not exists public.payment_audit_logs (
  id bigint generated by default as identity primary key,
  payment_id uuid references public.payments(id) on delete cascade,
  invoice_id text,
  event text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_audit_payment_idx on public.payment_audit_logs(payment_id, created_at desc);

create sequence if not exists public.taskora_invoice_sequence start 1;

create or replace function public.next_taskora_invoice_number()
returns text
language sql
security invoker
set search_path = public
as $$
  select 'TASK-' || to_char(current_date, 'YYYY') || '-' || lpad(nextval('public.taskora_invoice_sequence')::text, 6, '0');
$$;

revoke all on function public.next_taskora_invoice_number() from public, anon, authenticated;
grant execute on function public.next_taskora_invoice_number() to service_role;

create or replace function public.is_payment_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = (select auth.uid()) and role = 'admin'
  );
$$;

grant execute on function public.is_payment_admin() to authenticated;

alter table public.payment_settings enable row level security;
alter table public.payments enable row level security;
alter table public.invoices enable row level security;
alter table public.payment_audit_logs enable row level security;

create policy "payment settings readable"
on public.payment_settings for select
to authenticated
using (true);

create policy "payment settings admin update"
on public.payment_settings for update
to authenticated
using ((select public.is_payment_admin()))
with check ((select public.is_payment_admin()));

create policy "users read own payments"
on public.payments for select
to authenticated
using (user_id = (select auth.uid()) or (select public.is_payment_admin()));

create policy "users read own invoices"
on public.invoices for select
to authenticated
using (user_id = (select auth.uid()) or (select public.is_payment_admin()));

create policy "admins read payment audit"
on public.payment_audit_logs for select
to authenticated
using ((select public.is_payment_admin()));

-- Intentionally no INSERT/UPDATE/DELETE policies for normal authenticated users.
-- Server-side payment functions use the service role and are the only writers.

grant select on public.payment_settings to authenticated;
grant select on public.payments to authenticated;
grant select on public.invoices to authenticated;
grant select on public.payment_audit_logs to authenticated;

create or replace function public.get_payment_checkout_config(p_type text)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  s public.payment_settings%rowtype;
  price numeric(12,2);
begin
  select * into s from public.payment_settings where id = true;
  if not found then return jsonb_build_object('enabled', false); end if;

  if p_type = 'micro_jobs' then
    price := s.micro_job_activation_price;
  elsif p_type = 'verification' then
    if not s.verification_enabled then
      return jsonb_build_object('enabled', false, 'reason', 'verification_disabled');
    end if;
    price := s.verification_price;
  else
    price := null;
  end if;

  return jsonb_build_object(
    'enabled', s.payment_enabled,
    'providerName', s.provider_name,
    'currency', s.currency,
    'merchantName', s.merchant_name,
    'merchantLogo', s.merchant_logo,
    'supportPhone', s.support_phone,
    'supportEmail', s.support_email,
    'termsText', s.terms_text,
    'price', price
  );
end;
$$;

grant execute on function public.get_payment_checkout_config(text) to authenticated;

-- Called ONLY by trusted server code after the provider verification API confirms
-- invoice, amount and final paid status. Service-role access is required.
create or replace function public.finalize_verified_payment(
  p_payment_id uuid,
  p_transaction_id text,
  p_provider_transaction_id text,
  p_payment_method text,
  p_provider_response jsonb default '{}'::jsonb
)
returns public.payments
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  pay public.payments%rowtype;
  inv public.invoices%rowtype;
  order_id uuid;
begin
  select * into pay from public.payments where id = p_payment_id for update;
  if not found then raise exception 'payment_not_found'; end if;

  if pay.status = 'paid' then return pay; end if;
  if pay.status in ('cancelled','refunded') then raise exception 'payment_not_payable'; end if;

  if exists (select 1 from public.payments where transaction_id = p_transaction_id and id <> pay.id) then
    raise exception 'duplicate_transaction';
  end if;

  update public.payments
  set status = 'paid',
      transaction_id = p_transaction_id,
      provider_transaction_id = coalesce(p_provider_transaction_id, provider_transaction_id),
      payment_method = p_payment_method,
      provider_response = coalesce(p_provider_response, '{}'::jsonb),
      paid_at = coalesce(paid_at, now()),
      updated_at = now()
  where id = pay.id
  returning * into pay;

  update public.invoices
  set status = 'paid', transaction_id = pay.transaction_id,
      payment_method = pay.payment_method, paid_at = pay.paid_at
  where payment_id = pay.id
  returning * into inv;

  if pay.payment_type = 'micro_jobs' then
    insert into public.memberships (user_id, status, activated_at, activation_source)
    values (pay.user_id, 'active', pay.paid_at, 'payment')
    on conflict (user_id) do update
      set status = 'active', activated_at = excluded.activated_at, activation_source = 'payment';
  elsif pay.payment_type = 'verification' then
    update public.profiles set is_social_verified = true where id = pay.user_id;
  elsif pay.payment_type = 'reselling' and pay.item_id is not null then
    begin
      order_id := pay.item_id::uuid;
      update public.reselling_orders
      set status = case when status = 'cancelled' then status else 'processing' end
      where id = order_id and user_id = pay.user_id;
    exception when invalid_text_representation then
      null;
    end;
  end if;

  insert into public.payment_audit_logs(payment_id, invoice_id, event, details)
  values (pay.id, pay.invoice_id, 'payment_verified', jsonb_build_object('transaction_id', pay.transaction_id));

  -- Notification delivery is non-critical. A notification schema change must not
  -- roll back an otherwise verified payment or its purchased entitlement.
  begin
    insert into public.notifications(user_id, title, body, category)
    values (
      pay.user_id,
      'Payment successful',
      case
        when pay.payment_type = 'micro_jobs' then 'আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে। Micro Jobs অ্যাক্সেস সক্রিয় করা হয়েছে।'
        when pay.payment_type = 'verification' then 'আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে। Verified Badge সক্রিয় করা হয়েছে।'
        else 'আপনার পেমেন্ট সফলভাবে সম্পন্ন হয়েছে।'
      end,
      'wallet'
    );
  exception when others then
    insert into public.payment_audit_logs(payment_id, invoice_id, event, details)
    values (pay.id, pay.invoice_id, 'notification_failed', jsonb_build_object('message', sqlerrm));
  end;

  return pay;
end;
$$;

revoke all on function public.finalize_verified_payment(uuid,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.finalize_verified_payment(uuid,text,text,text,jsonb) to service_role;

create or replace function public.mark_payment_failed(
  p_payment_id uuid,
  p_event text,
  p_provider_response jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare pay public.payments%rowtype;
begin
  select * into pay from public.payments where id = p_payment_id for update;
  if not found or pay.status = 'paid' then return; end if;

  if p_event = 'cancelled' then
    update public.payments set status='cancelled', cancelled_at=now(), provider_response=p_provider_response, updated_at=now() where id=p_payment_id;
    update public.invoices set status='cancelled' where payment_id=p_payment_id;
  else
    update public.payments set status='failed', failed_at=now(), provider_response=p_provider_response, updated_at=now() where id=p_payment_id;
    update public.invoices set status='failed' where payment_id=p_payment_id;
  end if;

  insert into public.payment_audit_logs(payment_id, invoice_id, event, details)
  values (p_payment_id, pay.invoice_id, case when p_event='cancelled' then 'payment_cancelled' else 'payment_failed' end, p_provider_response);
end;
$$;

revoke all on function public.mark_payment_failed(uuid,text,jsonb) from public, anon, authenticated;
grant execute on function public.mark_payment_failed(uuid,text,jsonb) to service_role;
